/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit1;

import java.time.LocalDate;
import java.util.*;

public class App {
    public static void main(String[] args) {
        List<Pessoa> festinha = new ArrayList<Pessoa>() {
            {
                add(new Pessoa("Maria", LocalDate.of(2022, 10, 22)));
                add(new Pessoa("Matheus", LocalDate.of(1999, 10, 22)));
            }
        };

        for (Pessoa pessoa : festinha) {
            System.out.println(pessoa);
        }
    }
}
